//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int IdEndereco { get; set; }
        public int CidadeId { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Cep { get; set; }
        public string Complemento { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
