//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagemProduto
    {
        public int IdImagemProduto { get; set; }
        public string CaminhoImagem { get; set; }
        public int ProdutoId { get; set; }
        public Nullable<int> CarouselId { get; set; }
    
        public virtual Carousel Carousel { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
