//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCarrinho
    {
        public int IdItemCarrinho { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public int CarrinhoId { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Carrinho Carrinho { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
