//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IdLog { get; set; }
        public int TarefasId { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Tarefas Tarefas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
